server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: ordermanagement
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, /orderItems/**, /orderSummaries/**, /orderDetails/**, /orderItemLists/**, /orderItemDetails/**
        - id: InventoryManagement
          uri: http://localhost:8083
          predicates:
            - Path=/stocks/**, /stockStatusViews/**, /stockChangeHistories/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: ordermanagement
          uri: http://ordermanagement:8080
          predicates:
            - Path=/orders/**, /orderItems/**, 
        - id: InventoryManagement
          uri: http://inventoryManagement:8080
          predicates:
            - Path=/stocks/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
