---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanagement
  labels:
    app: ordermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanagement
  template:
    metadata:
      labels:
        app: ordermanagement
    spec:
      containers:
        - name: ordermanagement
          image: username/ordermanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: InventoryManagement
  labels:
    app: InventoryManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: InventoryManagement
  template:
    metadata:
      labels:
        app: InventoryManagement
    spec:
      containers:
        - name: InventoryManagement
          image: username/InventoryManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ordermanagement
  labels:
    app: ordermanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ordermanagement


---


apiVersion: v1
kind: Service
metadata:
  name: InventoryManagement
  labels:
    app: InventoryManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: InventoryManagement

